### ISSUE TITLE
SIG documentation is not rendered

### ISSUE THREAD

**Issue by codificat** [thoth-station/help#18]
When navigating to the documentation about the SIGs, their *README* files show up as the source markdown instead of being rendered.

Example: https://thoth-station.ninja/help/documentation/core/community/sig-user-experience/README.md

![imatge](https://user-images.githubusercontent.com/709574/169049909-6f77ccee-3db0-4be7-9b55-30d061527b72.png)

**Comment by Gkrumbach07** [comment]
This is a known issue. There is a problem with the markdown having different types of comments in the same document. I am looking into ways the Gatsby plugin can handle it.

**Comment by Gkrumbach07** [comment]
fixed in PR

issue is that some md files use a different style of comment.

comments formatted as `<!---COMMENT--->` instead of `<!--COMMENT-->` will not render correctly. However it will render as a mdx file but that means setting all files (.md and .mdx) to be formatted as a mdx file. There is no way to guarantee that all files will render without errors as mdx files. There is a better solution, but it may require some more digging.
